# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-24 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cutter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vcounter',
            name='unique_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vcounter',
            name='visit_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
